name: Swift Build Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    
    # Cache the build artifacts and dependencies
    - name: Cache Swift dependencies
      uses: actions/cache@v4.2.0
      with:
        path: |
          ~/.swiftpm
          .build
        key: ${{ runner.os }}-swift-${{ hashFiles('Package.swift') }}
        restore-keys: |
          ${{ runner.os }}-swift-

    - name: Build
      run: swift build -v

    - name: Run tests
      run: swift test -v
